core_bundle:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /
app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc
api:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    type: rest
    prefix: /api/