# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded.
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_SUPER_Admin: ROLE_SUPER_Admin
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_DIRECTOR: ROLE_DIRECTOR
        ROLE_SUPERVISOR: ROLE_SUPERVISOR
        ROLE_VISITOR: ROLE_VISITOR
        ROLE_USER: ROLE_USER


    providers:
        db_provider:
            entity:
                class: CoreBundle:User
                property: id

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(%api_lang%)/api/admin/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /(%api_lang%)/api/admin/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            security: false

        doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: true

        api:
            pattern:   ^/(%api_lang%)/api
            stateless: true
            provider: db_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
    acl:
        connection: default