<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends EntityRepository
{
}
