<?php

namespace CoreBundle\Repository;

/**
 * SupervisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupervisorRepository extends \Doctrine\ORM\EntityRepository
{
}
